language: r
r:
  - oldrel
  - release
  - devel

sudo: false
cache: packages

warnings_are_errors: true

r_packages:
  - devtools
  - testthat
  - rmarkdown

r_github_packages:
#  - duncantl/CodeDepends
   - jimhester/lintr
  
after_success:
  - Rscript -e 'covr::codecov()'
  - R CMD INSTALL $PKG_TARBALL
  - Rscript -e 'lintr::lint_package()'
