language: r
r:
  - oldrel
  - release
  - devel

sudo: false
cache: packages

warnings_are_errors: true

r_packages:
  - devtools
  - testthat

# bioc_packages:
#   - graph

r_github_packages:
  - ProvTools/provR
#  - duncantl/CodeDepends
  
after_success:
  - Rscript -e 'covr::codecov()'
