language: r
r:
  - oldrel
  - release
  - devel

sudo: false
cache: packages

warnings_are_errors: false

r_packages:
  - devtools
  - CodeDepends
  - testhat

r_github_packages:
  - ProvTools/provR
  
after_success:
  - Rscript -e 'covr::codecov()'
