language: r
r:
  - oldrel
  - release
  - devel

sudo: false
cache: packages

warnings_are_errors: false

r_packages:
  - devtools
  - testthat
  - graph

r_github_packages:
  - ProvTools/provR
  - duncantl/CodeDepends
  
after_success:
  - Rscript -e 'covr::codecov()'
